routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/','login');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('migrations','MigrationsController')->middleware('auth')->except(['edit']);
Route::get('search','MigrationsController@search')->middleware('auth')->name('migrations.search');
Route::get('activitylog','HomeController@logs')->middleware('auth')->name('actlogs');
Route::post('search','MigrationsController@search_action')->name('migrations.search.action')->middleware('auth');
Route::get('migrations/sorting/completed','MigrationsController@completed')->middleware('auth')->name('migrations.completed');
Route::get('migrations/sorting/scheduled','MigrationsController@scheduled')->middleware('auth')->name('migrations.scheduled');
Route::get('migrations/sorting/pending','MigrationsController@pending')->middleware('auth')->name('migrations.pending');
Route::get('migrations/sorting/cancelled','MigrationsController@cancelled')->middleware('auth')->name('migrations.cancelled');
Route::get('log','HomeController@log')->name('log');
Route::get('storage/{filename}',function($filename){
    // $path = storage_path($filename);
    $path = str_replace('public/','replace',$filename);
    if (!File::exists($path)) {
        abort(404);
    }

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
})->name('getFile');
// Route::get('email', function(){
// 	Mail::raw('Sending emails with Mailgun and Laravel is easy!', function($message)
// 	{
// 		$message->to('batrider69@gmail.com');
// 	});
// });
Route::resource('users','UserController')->except(['destroy']);


Route::get('reports/completed','ExcelController@completed')->name('reports.completed');
Route::get('reports/scheduled','ExcelController@scheduled')->name('reports.scheduled');
Route::get('reports/pending','ExcelController@pending')->name('reports.pending');
Route::get('reports/cancelled','ExcelController@cancelled')->name('reports.cancelled');
Route::get('reports/all','ExcelController@all')->name('reports.all');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
    protected function setPasswordAttribute($value)
    {
        $this->attributes['password'] = bcrypt($value);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;
use Auth;
use App\User;
use Illuminate\Http\Request;
use App\Models\ActivityLog;
class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('users.index')->with('users',User::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'email' => 'required|unique:users,email',
            'password' => 'required|confirmed'
        ]);
        $user = new User;
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = $request->password;
        $user->save();
        ActivityLog::create(['user_id' => Auth::user()->id , 'action' => 'Added user '.$user->id]);
        return back()->with('status','User added');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('users.show')->with('user',$user);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('users.edit')->with('user',$user);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $request->validate([
            'name' => 'required',
            'email' => 'required|email|unique:users,email,'.$user->id,
            'password' => 'nullable|confirmed'
        ]);
        $user->name = $request->name;
        $user->email = $request->email;
        if($request->password)
        {
            $user->password = $request>password;
        }
        $user->save();
        return back()->with('status','Profile updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
	<div class="card card-header">
		<div class="row">
			<div class="col-10">
				Add User
			</div>
			<div class="col-2">
				<a href="{{ route('users.index') }}" class="btn btn-sm btn-info float-right">Back</a>
			</div>
		</div>
	</div>
	<div class="card card-body">
		@include('shared.alerts')
		<form method="POST" action="{{ route('users.store') }}">
			{{ csrf_field() }}
			<div class="form row">
				<div class="col-6">
					<label for="name">Name</label>
					<input class ="form-control" type="text" name="name" id="name" value="{{ old('name') }}">
				</div>
				<div class="col-6">
					<label for="email">Email</label>
					<input class="form-control" type="text" name="email" id="name" value=" {{ old('email') }}">
				</div>
			</div>
			<div class="form row">
				<div class="col-6">
					<label for="password">Password</label>
					<input class ="form-control" type="password" name="password" id="password">
				</div>
				<div class="col-6">
					<label for="password_confirmation">Confirm Password:</label>
					<input class="form-control" type="password" name="password_confirmation" id="password_confirmation">
				</div>
			</div>
			<div class="form row mt-3">
				<div class="col-12">
					<button class="btn btn-info">Save</button>
				</div>
			</div>
		</form>
	</div>
	<div class="card card-footer">
		Date Today {{ Carbon\Carbon::now()->toDateString() }}
	</div>
</div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
	<div class="card card-dark">
		<div class="card-header">
			Updating My Profile
			<a href="{{ route('users.show',$user->id)}}" class="btn btn-sm btn-info float-right">Back</a>
		</div>
		<div class="card-body">
			@include('shared.alerts')
		<form method="POST" action="{{ route('users.update',['id' => $user->id]) }}">
			{{ csrf_field() }}
			{{ method_field('PUT')}}
			<div class="form row">
				<div class="col-6">
					<label for="name">Name</label>
					<input class ="form-control" type="text" name="name" id="name" value="{{ old('name') ?: $user->name }}">
				</div>
				<div class="col-6">
					<label for="email">Email</label>
					<input class="form-control" type="text" name="email" id="name" value=" {{ old('email') ?: $user->email }}">
				</div>
			</div>
			<div class="form row">
				<div class="col-6">
					<label for="password">Password</label>
					<input class ="form-control" type="password" name="password" id="password">
				</div>
				<div class="col-6">
					<label for="password_confirmation">Confirm Password:</label>
					<input class="form-control" type="password" name="password_confirmation" id="password_confirmation">
				</div>
			</div>
			<div class="form row mt-3">
				<div class="col-12">
					<button class="btn btn-info">Save</button>
				</div>
			</div>
		</form>
		</div>
	</div>
</div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
	<div class="card card-header">
		<div class="row">
			<div class="col-10">Users</div>
			<div class="col-2">
				<a href="{{ route('users.create') }}" class="btn btn-info float-right btn-sm">Create User</a>
			</div>
		</div>
	</div>
	<div class="card card-body">
		<table id="UsersTable" class="table table-bordered">
			<thead>
				<th>ID</th>
				<th>Name</th>
				<th>Email</th>
				<th>Date Created</th>
			</thead>
			<tbody>
				@foreach($users as $user)
				<tr>
					<td>{{ $user->id}}</td>
					<td>{{ $user->name }}</td>
					<td>{{ $user->email }}</td>
					<td>{{ $user->created_at->format('d-m-Y') }}</td>
				</tr>
				@endforeach
				
			</tbody>
		</table>
	</div>
	<div class="card card-footer">
		Updated as of {{ Carbon\Carbon::now()->toDateTimeString() }}
	</div>
</div>
@endsection

resources/views/users/show.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
	<div class="card card-info">
		<div class="card-header">My Profile</div>
		<div class="card-body">
			<div class="row">
				<div class="col-8">
					<p>
						<h5 class="inline">Name:</h5> {{ $user->name }}
					</p>
					<p>
						<h5 class="inline">Email:</h5> {{ $user->email }}
					</p>
				</div>
				<div class="col-4">
					<img src="{{ asset('uploads/acct.png') }}	">
				</div>
			</div>
		</div>
		<div class="card-footer">
			Last Update {{ $user->updated_at }}
			<a href='{{ route('users.edit',$user->id)}}' class="btn btn-info btn-sm float-right">Edit</a>
		</div>
	</div>
</div>
@endsection
@push('styles')
<style type="text/css">
	.inline{
		display: inline-block;
	}
</style>
@endpush