routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/','login');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('migrations','MigrationsController')->middleware('auth')->except(['edit']);
Route::get('search','MigrationsController@search')->middleware('auth')->name('migrations.search');
Route::get('activitylog','HomeController@logs')->middleware('auth')->name('actlogs');
Route::post('search','MigrationsController@search_action')->name('migrations.search.action')->middleware('auth');
Route::get('migrations/sorting/completed','MigrationsController@completed')->middleware('auth')->name('migrations.completed');
Route::get('migrations/sorting/scheduled','MigrationsController@scheduled')->middleware('auth')->name('migrations.scheduled');
Route::get('migrations/sorting/pending','MigrationsController@pending')->middleware('auth')->name('migrations.pending');
Route::get('migrations/sorting/cancelled','MigrationsController@cancelled')->middleware('auth')->name('migrations.cancelled');
Route::get('log','HomeController@log')->name('log');
Route::get('storage/{filename}',function($filename){
    // $path = storage_path($filename);
    $path = str_replace('public/','replace',$filename);
    if (!File::exists($path)) {
        abort(404);
    }

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
})->name('getFile');
// Route::get('email', function(){
// 	Mail::raw('Sending emails with Mailgun and Laravel is easy!', function($message)
// 	{
// 		$message->to('batrider69@gmail.com');
// 	});
// });
Route::resource('users','UserController')->except(['destroy']);


Route::get('reports/completed','ExcelController@completed')->name('reports.completed');
Route::get('reports/scheduled','ExcelController@scheduled')->name('reports.scheduled');
Route::get('reports/pending','ExcelController@pending')->name('reports.pending');
Route::get('reports/cancelled','ExcelController@cancelled')->name('reports.cancelled');
Route::get('reports/all','ExcelController@all')->name('reports.all');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    {{-- <link href="{{ asset('css/app.css') }}" rel="stylesheet"> --}}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">
    @stack('styles')
</head>
<body class="bg-white">
    <div id="app">
         <nav class="navbar navbar-expand-md navbar-dark bg-dark">
              <a class="navbar-brand" href="#">
                  {{ config('app.name', 'Laravel') }}
              </a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

              <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                <ul class="navbar-nav mr-auto">
                 @auth
                  <li class="nav-item {{ Nav::isRoute('home') }}">
                    <a class="nav-link" href="{{ route('home') }}">Home</a>
                  </li>
                  <li class="nav-item {{ Nav::isResource('migrations',null,'active') }} {{ Nav::isRoute('migrations.search') }}">
                    <a class="nav-link" href="{{ route('migrations.index') }}">Migrations</a>
                  </li>
                  <li class="nav-item {{ Nav::isRoute('log') }}">
                    <a class="nav-link" href="{{ route('log') }}">Activity Log</a>
                  </li>
                  <li class="nav-item {{ Nav::isResource('users',null,'active') }}">
                    <a class="nav-link" href="{{ route('users.index') }}">Users</a>
                  </li>
                 @endauth
                </ul>
                 <ul class="navbar-nav ml-auto">
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">My Account</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                      @if(Auth::check())
                          <a class="dropdown-item" href="{{ route('users.show',['id' => Auth::user()->id]) }}">My Profile</a>
                        <a class="dropdown-item" href="{{ route('logout') }}"
                                                    onclick="event.preventDefault();
                                                             document.getElementById('logout-form').submit();">
                                                    Logout</a>

                      <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                          {{ csrf_field() }}
                      </form>
                      @else
                      <a class="dropdown-item" href="{{ route('login') }}">Login</a>
                      @endif
                    </div>
                  </li>
                </ul>
              </div>
            </nav>          
       
                      

    </div>
    <div class="mt-3">
        @yield('content')
    </div>
    <!-- Scripts -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    @stack('scripts')
</body>
</html>